version: "3"

services:
  api:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:11.5
    volumes:
      - ./backend/postgres:/var/lib/postgresql/data
      - ./backend/dumps:/var/lib/postgresql/dumps
      - ./backend/seed-data.sh:/docker-entrypoint-initdb.d/seed-data.sh
    env_file: ./backend/.env
    ports:
      - "5432:5432"
